// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMQCB2aXf_-HRYIUdfjUT2xL4iNw-FYz0',
    appId: '1:1002867988520:web:9770d638bd4077be34fd1d',
    messagingSenderId: '1002867988520',
    projectId: 'magic-bakery-96415',
    authDomain: 'magic-bakery-96415.firebaseapp.com',
    storageBucket: 'magic-bakery-96415.appspot.com',
    measurementId: 'G-QP34TH55YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQQMOMzOlECzpdBl_ZkAK7umIaE1xp6ic',
    appId: '1:1002867988520:android:002b12dde819965934fd1d',
    messagingSenderId: '1002867988520',
    projectId: 'magic-bakery-96415',
    storageBucket: 'magic-bakery-96415.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSF9u0hyDGT4odAQaBpiaIgjbj5xNEuGU',
    appId: '1:1002867988520:ios:584baf148ac692c034fd1d',
    messagingSenderId: '1002867988520',
    projectId: 'magic-bakery-96415',
    storageBucket: 'magic-bakery-96415.appspot.com',
    iosBundleId: 'com.example.magicBakery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSF9u0hyDGT4odAQaBpiaIgjbj5xNEuGU',
    appId: '1:1002867988520:ios:3d4f36b7c8aee04f34fd1d',
    messagingSenderId: '1002867988520',
    projectId: 'magic-bakery-96415',
    storageBucket: 'magic-bakery-96415.appspot.com',
    iosBundleId: 'com.example.magicBakery.RunnerTests',
  );
}
